#!/usr/bin/env python3
import json
import subprocess
from pynput import keyboard

with open("/etc/creata/config.json", "r") as f:
    config = json.load(f)

hotkeys = {}

for bind in config["bindings"]:
    command = bind["command"]

    def make_callback(cmd):
        def callback():
            try:
                subprocess.Popen(
                    cmd,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            except FileNotFoundError:
                print(f"Invalid Arguments: {cmd[0]}")
        return callback

    hotkeys[bind["hotkey"]] = make_callback(command)

listener = keyboard.GlobalHotKeys(hotkeys)
listener.start()
listener.join()
