backend = "glx";
vsync = true;
corner-radius = 12;

wintypes:
{
  dock = { shadow = false; corner-radius = 0; full-shadow = false; };
  popup_menu = { shadow = true; corner-radius = 0; };
  dropdown_menu = { shadow = true; corner-radius = 0; };
};

shadow = true;
shadow-exclude = [
  "window_type = 'dock'"
];