#!/bin/sh
if test -z "$DBUS_SESSION_BUS_ADDRESS";
then
	eval $(dbus-launch --sh-syntax)
fi

lxpanel &

pcmanfm --desktop
# (sleep 2 && nm-tray) &
# (sleep 2 && cbatticon -n -u 5) &
# (sleep 2 && blueman-applet) &
# (sleep 2 && xbindkeys) &
# (sleep 2 && pasystray) &


exit 0
