#!/bin/sh
if test -z "$DBUS_SESSION_BUS_ADDRESS";
then
	eval $(dbus-launch --sh-syntax)
fi
eval $(gnome-keyring-daemon --start --components=secrets,ssh,gpg)
export SSH_AUTH_SOCK
picom &
/usr/essentials/menu -nurl /usr/share/dsyl/menubar.html &
/usr/essentials/keyver &
/usr/essentials/mola/mola-desktop &
lua /usr/core/init.lua &

pcmanfm --desktop &
exit 0
