#!/bin/sh
if test -z "$DBUS_SESSION_BUS_ADDRESS";
then
	eval $(dbus-launch --sh-syntax)
fi
eval $(gnome-keyring-daemon --start --components=secrets,ssh,gpg)
export SSH_AUTH_SOCK

python3 /usr/essentials/menu.py &

lxpanel &

pcmanfm --desktop
(sleep 2 && nm-tray) &
(sleep 2 && cbatticon -n -u 5) &
# (sleep 2 && blueman-applet) &
# (sleep 2 && xbindkeys) &
# (sleep 2 && pasystray) &


exit 0
